FROM alpine:3.5

RUN apk add --no-cache php7.1-fpm php7-redis php7-gmagick php7-apcu php7-xml \
        php7-phar php7-openssl php7.1-mysqli php7.1-curl php7.1-gmp php7.1-iconv \
        php7.1-dom php7.1-gd php7.1-bcmath php7.1-mcrypt php7.1-mbstring php7.1-ldap \
        php7.1-json php7.1-intl php7.1-imap php7.1-session
