---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: nginx-sites-enabled-conf
          configMap:
            name: nginx-sites-enabled-conf
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
            - name: nginx-sites-enabled-conf
              mountPath: /etc/nginx/sites-enabled
          resources:
            requests:
              memory: "200Mi"
              cpu: "250m"
            limits:
              memory: "5000Mi"
              cpu: "500m"
